include: 
  - project: "$CICD_PROJECT"
    ref: main
    file: "$CICD_GITLAB_YML"

stages:
  - Provision
  - Compile
  - Build
  - Retag
  - Rollout

variables:
  IMAGESTREAM_NAME: ${IMAGESTREAM_NAME}
  ROLLOUT_APP: ${ROLLOUT_APP}

.provision:
  script:
    - "helm upgrade --install buergeransicht charts/buergeransicht --namespace $ENVIRONMENT --values=values-base.yaml --values=values-${ENVIRONMENT}.yaml"

Compile:
  extends: .build-envs
  image: registry.access.redhat.com/ubi8/nodejs-16
  stage: Compile
  tags: [ "${RUNNER_TAG}" ]
  variables:
    NO_PROXY: '${PROXY_NO_PROXY}'
    HTTP_PROXY: '${PROXY_HTTP_PROXY}'
    HTTPS_PROXY: '${PROXY_HTTPS_PROXY}'
    no_proxy: '${PROXY_NO_PROXY}'
    http_proxy: '${PROXY_HTTP_PROXY}'
    https_proxy: '${PROXY_HTTPS_PROXY}'
  only:
    variables:
      - $ENVIRONMENT == $CI_COMMIT_BRANCH
  script:
    - 'rm -f "package-lock.json"'
    - 'npm install --include=dev'
    - 'npm run build'
    - "sed -i 's/http:\\/\\/localhost:8082/\\/buergeransicht/g' dist/index.html"
  artifacts:
    paths:
      - dist
    expire_in: 1 week

.build:
  script:
    - "oc start-build ${IMAGESTREAM_NAME} --from-dir=dist -Fw"
