spring:

  # Define the local keycloak realm here
  realm: ${REALM}

  logging:
    level:
      org.springframework.cloud.gateway.filter.NettyWriteResponseFilter: DEBUG

  # spring cloud gateway config
  cloud:
    gateway:
      actuator:
        verbose:
          enabled: false
      globalcors:
        corsConfigurations:
          # The cors configuration to allow frontend developers cross origin request via this api gateway
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
              - "http://127.0.0.1:8080"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: backend
          uri: ${BACKEND_URI}
          predicates:
            - Path=${BACKEND_URI_PREDICATE}
          filters:
            - RewritePath=${BACKEND_URI_REWRITE_PATH}
            - RemoveResponseHeader=WWW-Authenticate
      default-filters:
        - RemoveResponseHeader=Expires
        - RemoveRequestHeader=cookie
        - RemoveRequestHeader=x-xsrf-token
        - TokenRelay=

  http:
    log-request-details: on

server:
  port: 8082
