apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-nginx-config
data:
    # add_header 'Access-Control-Allow-Origin' 'origin';
  cors.conf: |-
{{- if .Values.nginx }}
{{- if .Values.nginx.cors }}
    location / {
      if ($http_origin ~* "^https?://({{ join "|" .Values.nginx.cors }})$") {
          add_header Access-Control-Allow-Origin "$http_origin";
      }
    }
{{- end }}
{{- end }}
