{{- range $k, $v := .Values.routes }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ $.Release.Name }}
  annotations:
    haproxy.router.openshift.io/rewrite-target: "/"
  {{- with $v.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $.Release.Name }}-{{ $k }}
spec:
  host: {{ $v.host }}
  path: {{ $v.path }}
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ $.Release.Name }}
    weight: 100
  wildcardPolicy: None
{{- end }}